#!/bin/bash

TM2_ROOT=$(cd $(dirname "$BASH_SOURCE") && pwd)
MDK_ROOT=$(pwd)
MDK_NAME=mdk-17.04.5.tar.gz
MDK_CANONICAL=mdk_release_17.04.5_general_purpose
MDK_URL=http://artifactoryperc01.iil.intel.com:8081/artifactory/libs-release-local/movidius/mdk/mdk/17.04.05/$MDK_NAME

export MDK_INSTALL_DIR=$MDK_ROOT/external/

export MV_COMMON_BASE=$MDK_ROOT/external/$MDK_CANONICAL/mdk/common
export MV_TOOLS_DIR=$MDK_ROOT/external/$MDK_CANONICAL/tools
export MV_TOOLS_VERSION=00.83.4
#export MV_SOC_REV=ma2450
export MV_SOC_REV=ma2150
if type -p ccache 1>/dev/null 2>/dev/null; then
    export MV_USE_CCACHE=1
fi

# Check for cross-compilation toolchain
if [[ ! -d $MDK_INSTALL_DIR/$MDK_CANONICAL ]]; then
	echo "WARNING: No MDK found in $MDK_INSTALL_DIR/$MDK_CANONICAL. Trying to download."

	TMP=$MDK_ROOT/external/.mdk
	mkdir -p $TMP
	pushd $TMP
	if [[ ! -f $MDK_NAME ]]; then
		curl -O $MDK_URL
	fi
	echo "Untaring MDK."
	tar xzf $MDK_NAME
	mv $MDK_CANONICAL $MDK_INSTALL_DIR/$MDK_CANONICAL
	popd
fi

# Check if all patches have been added
pushd $MDK_INSTALL_DIR/$MDK_CANONICAL
QUILT_PATCHES=$(realpath --relative-to=. $TM2_ROOT/mdk_patches) quilt pop -a -f
QUILT_PATCHES=$(realpath --relative-to=. $TM2_ROOT/mdk_patches) quilt push -a
popd

if [[ -d /etc/udev/rules.d ]]; then
    # Install udev rules
    echo "Checking udev rules"
    INSTALLED=false
    for RULE in $TM2_ROOT/udev/*.rules
    do
        RULEFILE=`basename $RULE`
        if [ ! -f /etc/udev/rules.d/$RULEFILE ]; then
            echo "Installing udev rule $RULEFILE"
            sudo cp $RULE /etc/udev/rules.d/$RULEFILE
            sudo chmod +x /etc/udev/rules.d/$RULEFILE
            INSTALLED=true
        fi
    done
    if [ "$INSTALLED" = true ]; then
        echo "Reloading udev, unplug and replug your devices"
        sudo udevadm control --reload
    else
        echo "All udev rules already installed"
    fi
fi
