#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.5 on Sat Aug 18 12:45:32 2012

import wx

# begin wxGlade: extracode
from render import MyGLCanvas
from ImagePanel import ImagePanel
import cor
from plot import *


# end wxGlade


class vis_gui(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: vis_gui.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.window_1 = wx.SplitterWindow(self, -1, style=wx.SP_3D | wx.SP_BORDER)
        self.window_1_pane_1 = wx.Panel(self.window_1, -1)
        self.render_widget = MyGLCanvas(self.window_1_pane_1, -1)
        self.window_2 = wx.SplitterWindow(self.window_1, -1, style=wx.SP_3D | wx.SP_BORDER)
        self.image_widget = ImagePanel(self.window_2, -1)
        self.window_2_pane_2 = wx.Panel(self.window_2, -1)
        self.window_3 = PlotNotebook(self.window_2_pane_2, -1)
        self.button_pause = wx.Button(self, -1, "Pause")
        self.button_play = wx.Button(self, -1, "Play")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnPause, self.button_pause)
        self.Bind(wx.EVT_BUTTON, self.OnPlay, self.button_play)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: vis_gui.__set_properties
        self.SetTitle("frame_1")
        self.SetSize((919, 605))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: vis_gui.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.render_widget, 1, wx.EXPAND, 0)
        self.window_1_pane_1.SetSizer(sizer_2)
        sizer_4.Add(self.window_3, 1, wx.EXPAND, 0)
        self.window_2_pane_2.SetSizer(sizer_4)
        self.window_2.SplitHorizontally(self.image_widget, self.window_2_pane_2)
        self.window_1.SplitVertically(self.window_1_pane_1, self.window_2)
        sizer_1.Add(self.window_1, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.button_pause, 0, 0, 0)
        grid_sizer_1.Add(self.button_play, 0, 0, 0)
        sizer_1.Add(grid_sizer_1, 0, 0, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def OnPause(self, event):  # wxGlade: vis_gui.<event_handler>
        print "Event handler `OnPause' not implemented!"
        cor.cor_time_pb_pause()

        event.Skip()

    def OnPlay(self, event):  # wxGlade: vis_gui.<event_handler>
        print "Event handler `OnPlay' not implemented!"
        cor.cor_time_pb_unpause()
        event.Skip()

# end of class vis_gui
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = vis_gui(None, -1, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
