#pragma once

#define ENABLE_SHAVE_TRACKER
#define ENABLE_SHAVE_STEREO_MATCHING
#define ENABLE_SHAVE_CHOLESKY
//#define ENABLE_SHAVE_PROJECT_OBSERVATION_COVARIANCE
//#define ENABLE_SHAVE_PROJECT_MOTION_COVARIANCE
#define ENABLE_BLIS_GEMM

//#define ENABLE_SHAVE_CHOLESKY_TEST
//#define ENABLE_SHAVE_PROJECT_MOTION_COVARIANCE_TEST
