find_library(ALLOY_SLIMAPI slimAPI)
find_library(ALLOY_HAL motionHAL)
find_library(ALLOY_INFRA infra)
find_path(ALLOY_INCLUDE MotionAPI.h)
find_package_handle_standard_args(alloy DEFAULT_MSG ALLOY_INCLUDE ALLOY_SLIMAPI ALLOY_INFRA ALLOY_HAL)
if (NOT TARGET alloy)
  add_library(alloy INTERFACE)
  target_include_directories(alloy INTERFACE ${ALLOY_INCLUDE})
  target_link_libraries(alloy INTERFACE ${ALLOY_SLIMAPI} ${ALLOY_HAL} ${ALLOY_INFRA})
endif()
