cmake_minimum_required(VERSION 3.7)

set(CMAKE_SYSTEM_NAME Android)

if (NOT CMAKE_SYSTEM_VERSION)
  set(CMAKE_SYSTEM_VERSION 21)
endif()

if (NOT CMAKE_ANDROID_ARCH_ABI)
  set(CMAKE_ANDROID_ARCH_ABI x86_64)
endif()

set(CMAKE_ANDROID_STL_TYPE c++_shared)

set(CMAKE_ANDROID_NDK_TOOLCHAIN_VERSION clang)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH) # ccache

add_definitions(-DANDROID)
