find_library(BLIS_LIBRARY blis)
find_path(BLIS_INCLUDE blis.h HINTS PATH_SUFFIXES blis)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(blis DEFAULT_MSG BLIS_INCLUDE BLIS_LIBRARY)
if(BLIS_FOUND AND NOT TARGET blis)
  add_library(blis INTERFACE)
  target_include_directories(blis INTERFACE ${BLIS_INCLUDE})
  target_link_libraries(blis INTERFACE ${BLIS_LIBRARY})
endif()
