//  qr.cpp
//
//  Created by Brian on 12/9/14.
//  Copyright (c) 2014 RealityCap. All rights reserved.
//
//  Adapted from /cpp/cli/src/main.cpp

#include "qr.h"
#include "filter.h"

#ifndef WIN32
#include <zxing/Result.h>
#include <zxing/ReaderException.h>
#include <zxing/common/IllegalArgumentException.h>
#include <zxing/BinaryBitmap.h>
#include <zxing/DecodeHints.h>
#include <zxing/qrcode/QRCodeReader.h>
#include <zxing/multi/qrcode/QRCodeMultiReader.h>
#include <zxing/common/HybridFastBinarizer.h>

using namespace std;
using namespace zxing;
using namespace zxing::multi;
using namespace zxing::qrcode;

vector<Ref<Result> > decode(Ref<BinaryBitmap> image, DecodeHints hints) {
    Ref<Reader> reader(new QRCodeReader);
    return vector<Ref<Result> >(1, reader->decode(image, hints));
}

vector<Ref<Result> > decode_multi(Ref<BinaryBitmap> image, DecodeHints hints) {
    QRCodeMultiReader reader;
    return reader.decodeMultiple(image, hints);
}

vector<Ref<Result> > detect_qr(const char * image, int width, int height) {
    vector<Ref<Result> > results;
    string cell_result;
    int res = -1;
    bool search_multi = false;

    try {
        Ref<Binarizer> binarizer;
        Ref<LuminanceSource> source(new DummyLuminanceSource(width, height));
        binarizer = new HybridFastBinarizer(image, width, height, source);
        DecodeHints hints(DecodeHints::DEFAULT_HINT);
        hints.setTryHarder(false);
        Ref<BinaryBitmap> binary(new BinaryBitmap(binarizer));
        if (search_multi) {
            results = decode_multi(binary, hints);
        } else {
            results = decode(binary, hints);
        }
        res = 0;
    } catch (const ReaderException& e) {
        cell_result = "zxing::ReaderException: " + string(e.what());
        res = -2;
    } catch (const zxing::IllegalArgumentException& e) {
        cell_result = "zxing::IllegalArgumentException: " + string(e.what());
        res = -3;
    } catch (const zxing::Exception& e) {
        cell_result = "zxing::Exception: " + string(e.what());
        res = -4;
    } catch (const std::exception& e) {
        cell_result = "std::exception: " + string(e.what());
        res = -5;
    }

    /*
    for (size_t i = 0; i < results.size(); i++) {
        cout << "  Format: " << BarcodeFormat::barcodeFormatNames[results[i]->getBarcodeFormat()];
        for (int j = 0; j < results[i]->getResultPoints()->size(); j++) {
            cout << "  Point[" << j <<  "]: "
            << results[i]->getResultPoints()[j]->getX() << " "
            << results[i]->getResultPoints()[j]->getY() << endl;
        }
        cout << results[i]->getText()->getText() << endl;
    }
    */

    return results;
}

bool qr_detect_one(const uint8_t * image, int width, int height, struct qr_detection & d)
{
    vector<Ref<Result> > results = detect_qr((const char *)image, width, height);
    if(results.size() > 0) {
        ArrayRef<Ref<zxing::ResultPoint> > res = results[0]->getResultPoints();
        if(res->size() == 4) {
            d.lower_left.x() = res[0]->getX();
            d.lower_left.y() = res[0]->getY();
            d.upper_left.x() = res[1]->getX();
            d.upper_left.y() = res[1]->getY();
            d.upper_right.x() = res[2]->getX();
            d.upper_right.y() = res[2]->getY();
            d.lower_right.x() = res[3]->getX();
            d.lower_right.y() = res[3]->getY();
            d.modules = results[0]->getVersion()*4 + 17; // size of qr code is defined by the version
            Ref<zxing::String> data = results[0]->getText();
            d.data = data->getText();
            return true;
        }
        else {
            fprintf(stderr, "Warning: qr detected, but with %d points\n", res->size());
        }
    }

    return false;
}

#else // if WIN32
bool qr_detect_one(const uint8_t * image, int width, int height, struct qr_detection & d)
{
	return false;
}
#endif

#include "homography.h"

/*
 * Computes a homography between calibrated image points and a fake image.
 * The fake image is generated by a virtual camera located at the world
 * coord (0, 0, -1), aligned with the world axis, looking at a qr code on the
 * plane z=0.
 *
 * This homography is decomposed into a rotation and translation, which is
 * the rotation and translation to bring a point from the virtual
 * camera frame to the camera frame which generated the calibrated points.
 *
 * The translation is then composed with a translation from the origin of the
 * fake camera to its image plane, so the resulting R&T represent the
 * transformation required to take the camera which took the calibrated
 * points to the center of the qr code.
 *
 * qr_size is the width in meters of the qr code in world coordinates.
 *
 * R and T provided by qr code transform: X_cam = Rq * X_new_world + Tq
 * Saved transformation: X_old_world = Rs * X_cam + Ts
 *
 * So result is X_old_world = Rs * (Rq * X_new_world + Tq) + Ts
 * We want zaxis new = zaxis old, so we will find an Rd that aligns them, and set Rq = Rq * Rd
 */

bool qr_code_homography(const struct filter *f, struct qr_detection detection, float qr_size_m, transformation & T)
{
    feature_t image_corners[4];
    feature_t calibrated[4];

    image_corners[0] = detection.upper_left;
    image_corners[1] = detection.lower_left;
    image_corners[2] = detection.lower_right;
    image_corners[3] = detection.upper_right;
    for(int c = 0; c < 4; c++) {
        calibrated[c] = f->s.camera_intrinsics.undistort_feature(f->s.camera_intrinsics.normalize_feature(image_corners[c]));
    }

    m3 Rq; v3 Tq;
    if(homography_align_to_qr(calibrated, qr_size_m, detection.modules, Rq, Tq)) {
        T = transformation(Rq, Tq);
        return true;
    }
    return false;
}

bool qr_code_origin(const struct filter *f, struct qr_detection detection, float qr_size_m, transformation & origin)
{
    transformation qr;
    if(qr_code_homography(f, detection, qr_size_m, qr)) {
        transformation world = transformation(f->s.Q.v, f->s.T.v);
        transformation world_qr = compose(world, qr);
        origin = invert(world_qr);
        return true;
    }
    else
        return false;
}

void qr_detector::process_frame(const struct filter * f, const uint8_t * image, int width, int height)
{
    qr_detection d;
    if(qr_detect_one(image, width, height, d)) {
        if(data.empty() || (d.data == data)) {
            if(qr_code_origin(f, d, size_m, origin)) {
                data = d.data;
                running = false;
                valid = true;
            }
        }
    }
}

void qr_benchmark::process_frame(const struct filter * f, const uint8_t * image, int width, int height)
{
    qr_detection d;
    transformation t_qr;
    if(qr_detect_one(image, width, height, d)) {
        if(qr_code_homography(f, d, size_m, t_qr)) {
            if(!origin_valid) {
                origin_valid = true;

                origin_qr = t_qr;
                origin_state = transformation(f->s.Q.v, f->s.T.v);
            }
            else {
                transformation now_qr = t_qr;
                transformation now_state = transformation(f->s.Q.v, f->s.T.v);

                transformation now_state_est = compose(origin_state, compose(origin_qr, invert(now_qr)));

                quaternion dQ = now_state_est.Q * now_state.Q.conjugate();
                v3 dT = now_state_est.T - dQ * now_state.T;
                cerr << "dR=" << dQ.toRotationMatrix() << ";\n";
                cerr << "dT=" << dT << ";\n";
                cerr << "norm(dT)=" <<dT.norm() << endl;
            }
        }
    }
}
