#pragma once

#define MAXSTATESIZE 86

#define BASEMOTIONSTATES 6
#define FAKESTATES 2

#define MAX_IMUS 2
#define MIN_IMUS 1
#define MIN_GROUPS 1
#define MAX_GROUPS ((MAXSTATESIZE - BASEMOTIONSTATESIZE - MIN_IMUS*6) / (6+1))
#define BASEMOTIONSTATESIZE (BASEMOTIONSTATES*3)
#define FAKESTATESIZE (FAKESTATES*3)

#define MAX_FAST_PATH_STATESIZE (BASEMOTIONSTATESIZE + MAX_IMUS*6)
#define MIN_SLOW_PATH_STATESIZE (BASEMOTIONSTATESIZE + MIN_IMUS*6 + MIN_GROUPS*6)

#define MAXOBSERVATIONS (MAXSTATESIZE - MIN_SLOW_PATH_STATESIZE)
#define MAXOBSERVATIONSIZE (2*MAXOBSERVATIONS)

#define MAX_STANDBY_TRACKS (2*MAXOBSERVATIONS)
